---
title: "Week_04b_Lecture Notes"
author: "Jordan Vest"
date: "2025-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Learning about dates and times from the {lubridate} package

```{r}
#Packages
install.packages("lubridate") # package to deal with dates and times
#Load libraries
library(tidyverse)
library(here)
library(lubridate)

```

now() #what time is it now?
now(tzone = "EST") # what time is it on the east coast
now(tzone = "GMT") # what time in GMT
###
now()
today(tzone = "GMT")
am(now()) #is it morning
leap_year(now()) #is it a leap year

Date	                    Function
2021-02-24	              ymd()
02/24/2021	              mdy()
February 24 2021          mdy()
24/02/2021	              dmy()
2021-02-24 10:22:20 PM	  ymd_hms()
02/24/2021 22:22:20	      mdy_hms()
February 24 2021 10:22 PM	mdy_hm()

```{r}
# make a character string
datetimes<-c("02/24/2021 22:22:20", 
             "02/25/2021 11:21:10", 
             "02/26/2021 8:01:52") 
# convert to datetimes
datetimes <- mdy_hms(datetimes) 
month(datetimes) #gives month number
month(datetime, label = TRUE) #gives month name and in calendar year, makes month vector not alphabetical
month(datetime, label = TRUE, abbr = FALSE) #abbreviated month
day(datetimes) #extract day
wday(datetimes, label = TRUE) # extract day of week
hour(datetimes)
minute(datetimes)
second(datetimes)
# add time
datetimes + hours(4) # this adds 4 hours (ex. your sensor was in a different timezone)
datetimes + days(2) # this adds 2 days; day() extracts the hour component from a time and days() is used to add hours to a datetime
# round time
round_date(datetimes, "minute") # round to nearest minute
round_date(datetimes, "5 mins") # round to nearest 5 minute
```

```{r}
# Challenge
#Packages
install.packages("lubridate") # package to deal with dates and times
#Load libraries
library(tidyverse)
library(here)
library(lubridate)
#Read in conductivity data
CondData<-read_csv(here("Week_05","Data", "CondData.csv"))
#convert date column to a datetime
CondData_datetime<-CondData %>%
   mutate(date= mdy_hms(date))
  
  
```